const expoTempo = [
  {
    date: "01 - 30 novembre",
    month: 11,
    year: 2022,
    time: "",
    name: "Vers un numérique responsable",
    author: "John Doe - Carl Moulin - Sarah Dresner",
    img: "img5.jpeg",
  },
  {
    date: "08 Janvier - 12 février",
    month: 1,
    year: 2023,
    time: "",
    name: "Insights",
    author: "Amélie Paul - Noura - Emilie Node",
    img: "img14.jpeg",
  },
  {
    date: "21 - 22 Janvier",
    month: 1,
    year: 2023,
    time: "",
    name: "Digitalks - Web3",
    author: "Edouard Desmin - Jacob Martin",
    img: "img10.jpeg",
  },
  {
    date: "19 - 26 février",
    month: 2,
    year: 2023,
    time: "",
    name: "Au delà du réel",
    author: "Lynn Williams - Elena Plat",
    img: "img12.jpeg",
  },
  {
    date: "01 - 25 mars",
    month: 3,
    year: 2023,
    time: "",
    name: "Digitalising contemporary art",
    author: "Collectif ASP",
    img: "img6.jpeg",
  },
  {
    date: "25 - 26 mars",
    month: 3,
    year: 2023,
    time: "/ 21h00 - 02h00",
    name: "Les soirs éléctroniques",
    author: "Machine B2B IDE",
    img: "img2.jpeg",
  },
  {
    date: "25 - 26 mars",
    month: 4,
    year: 2023,
    time: "",
    name: "Innovatove Display",
    author:
      "Camille Carpenter - David Swerner - Dominique Sacher - Rachel Duik",
    img: "img1.jpeg",
  },
  {
    date: "06 - 27 mai",
    month: 5,
    year: 2023,
    time: "",
    name: "In Real Life",
    author: "Roger Johns - Dorothy Hall - Matthew Krug",
    img: "home.png",
  },
  {
    date: "19 - 24 juin",
    month: 6,
    year: 2023,
    time: "",
    name: "Abysses",
    author: "Judy Sacot - Jennifer Benedict",
    img: "img7.jpeg",
  },
  {
    date: "28 juin - 13 juillet",
    month: 6,
    year: 2023,
    time: "",
    name: "Horizon numériques",
    author: "Michael Smith - John Doe - Susan Wadell",
    img: "img15.jpeg",
  },
  {
    date: "16 - 17 juillet",
    month: 7,
    year: 2023,
    time: "/ 21h00 - 02h00",
    name: "Les soirs éléctroniques",
    author: "Elevator - Charlotte Lens",
    img: "img9.jpeg",
  },
  {
    date: "29 - 12 Aout",
    month: 7,
    year: 2023,
    time: "",
    name: "Immersive places",
    author: "Willa Nalley - Salomé Santon",
    img: "img3.jpeg",
  },

];


const expoPerm = [
  {
    date: "",
    month: "",
    year: "",
    time: "",
    name: "Fragments",
    author:
      "Ryan Norris - David Deschemin - Judith Bruno - Carla Coutier - Catherine Crawford",
    img: "img4.jpeg",
  },
  {
    date: "",
    month: "",
    year: "",
    time: "",
    name: "Sans frontières",
    author:
      "Lori Human - Dan Miller - Michael Onil - Edward Hardy - Roderick Campbell",
    img: "img8.jpeg",
  },
  {
    date: "",
    month: "",
    year: "",
    time: "",
    name: "Visions troubles",
    author: "Sasha Gauvun - Martin Pilat - Elodie Martinez",
    img: "img11.jpeg",
  },
];
